/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Control.GestionFactura;
import Control.GestionZonaComun;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MenuPropietario extends javax.swing.JFrame {
    String idPropietario;
    String zonaComun;
    /**
     * Creates new form Factura
     */
    public MenuPropietario(String idPropietario) {
        
        this.idPropietario = idPropietario;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnFacturaMensual = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnMultas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnReservas = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnFacturaMensual2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFacturaMensual1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(203, 218, 213));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\Urbanizacion\\src\\main\\java\\Imagenes\\flecha.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\Urbanizacion\\src\\main\\java\\Imagenes\\flecha.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\Urbanizacion\\src\\main\\java\\Imagenes\\flecha.png")); // NOI18N

        btnFacturaMensual.setBackground(new java.awt.Color(86, 105, 129));
        btnFacturaMensual.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturaMensual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacturaMensual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturaMensualMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Factura mensual de mi propiedad");

        javax.swing.GroupLayout btnFacturaMensualLayout = new javax.swing.GroupLayout(btnFacturaMensual);
        btnFacturaMensual.setLayout(btnFacturaMensualLayout);
        btnFacturaMensualLayout.setHorizontalGroup(
            btnFacturaMensualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFacturaMensualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnFacturaMensualLayout.setVerticalGroup(
            btnFacturaMensualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnMultas.setBackground(new java.awt.Color(86, 105, 129));
        btnMultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mis multas a pagar");

        javax.swing.GroupLayout btnMultasLayout = new javax.swing.GroupLayout(btnMultas);
        btnMultas.setLayout(btnMultasLayout);
        btnMultasLayout.setHorizontalGroup(
            btnMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMultasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnMultasLayout.setVerticalGroup(
            btnMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        btnReservas.setBackground(new java.awt.Color(86, 105, 129));
        btnReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReservasMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Reservar zona común");

        javax.swing.GroupLayout btnReservasLayout = new javax.swing.GroupLayout(btnReservas);
        btnReservas.setLayout(btnReservasLayout);
        btnReservasLayout.setHorizontalGroup(
            btnReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
        );
        btnReservasLayout.setVerticalGroup(
            btnReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\Urbanizacion\\src\\main\\java\\Imagenes\\flecha.png")); // NOI18N

        btnFacturaMensual2.setBackground(new java.awt.Color(86, 105, 129));
        btnFacturaMensual2.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturaMensual2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacturaMensual2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturaMensual2MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Horarios de zonas comunes");

        javax.swing.GroupLayout btnFacturaMensual2Layout = new javax.swing.GroupLayout(btnFacturaMensual2);
        btnFacturaMensual2.setLayout(btnFacturaMensual2Layout);
        btnFacturaMensual2Layout.setHorizontalGroup(
            btnFacturaMensual2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFacturaMensual2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnFacturaMensual2Layout.setVerticalGroup(
            btnFacturaMensual2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\Urbanizacion\\src\\main\\java\\Imagenes\\flecha.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        btnFacturaMensual1.setBackground(new java.awt.Color(86, 105, 129));
        btnFacturaMensual1.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturaMensual1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacturaMensual1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturaMensual1MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pagar mis facturas");

        javax.swing.GroupLayout btnFacturaMensual1Layout = new javax.swing.GroupLayout(btnFacturaMensual1);
        btnFacturaMensual1.setLayout(btnFacturaMensual1Layout);
        btnFacturaMensual1Layout.setHorizontalGroup(
            btnFacturaMensual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFacturaMensual1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnFacturaMensual1Layout.setVerticalGroup(
            btnFacturaMensual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFacturaMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFacturaMensual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFacturaMensual2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnFacturaMensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel4)
                    .addComponent(btnReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnFacturaMensual2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnFacturaMensual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturaMensual2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMensual2MouseClicked
        String[] zonas = {"Piscina", "Cancha de basquet", "Cancha de futbol"};
        String zonaSeleccionada = (String) JOptionPane.showInputDialog(null, "Selecciona una zona común:",
            "Selector de zona común", JOptionPane.QUESTION_MESSAGE, null, zonas, zonas[0]);

        JOptionPane.showMessageDialog(null, "Has seleccionado: " + zonaSeleccionada);
        GestionZonaComun gzc = new GestionZonaComun();
        gzc.observarHorario(zonaSeleccionada);

    }//GEN-LAST:event_btnFacturaMensual2MouseClicked

    private void btnReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasMouseClicked
        String[] zonas = {"Piscina", "Cancha de basquet", "Cancha de futbol"};
        String zonaSeleccionada = (String) JOptionPane.showInputDialog(null, "Selecciona una zona común:",
            "Selector de zona común", JOptionPane.QUESTION_MESSAGE, null, zonas, zonas[0]);

        this.zonaComun = zonaSeleccionada;
        JOptionPane.showMessageDialog(null, "Has seleccionado: " + zonaSeleccionada);
        ReservaZonaComun ventanaReservaZonaComun = new ReservaZonaComun(this.idPropietario, this.zonaComun);
        ventanaReservaZonaComun.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReservasMouseClicked

    private void btnFacturaMensualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMensualMouseClicked
        Object[] opcionesTerminos = {"Descargar", "Cancelar"};
        int seleccionTerminos = JOptionPane.showOptionDialog(null, "¿Deseas descargar tu factura mensual?", "Aceptar/Rechazar",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcionesTerminos, opcionesTerminos[0]);
        if (seleccionTerminos == JOptionPane.YES_OPTION) {
            GestionFactura gf = new GestionFactura();
            gf.descargarFacturaMensual(this.idPropietario);
        } else if (seleccionTerminos == JOptionPane.NO_OPTION) {
            return;
        }
    }//GEN-LAST:event_btnFacturaMensualMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Object[] opcionesTerminos = {"Descargar", "Cancelar"};
        int seleccionTerminos = JOptionPane.showOptionDialog(null, "¿Deseas descargar tu factura mensual?", "Aceptar/Rechazar",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcionesTerminos, opcionesTerminos[0]);
        if (seleccionTerminos == JOptionPane.YES_OPTION) {
            GestionFactura gf = new GestionFactura();
            gf.descargarFactura(this.idPropietario);
        } else if (seleccionTerminos == JOptionPane.NO_OPTION) {
            return;
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnFacturaMensual1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMensual1MouseClicked
        Object[] opcionesTerminos = {"Pagar", "Cancelar"};
        int seleccionTerminos = JOptionPane.showOptionDialog(null, "¿Deseas pagar tus facturas mensuales?", "Aceptar/Rechazar",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcionesTerminos, opcionesTerminos[0]);
        if (seleccionTerminos == JOptionPane.YES_OPTION) {
            GestionFactura gf = new GestionFactura();
            gf.pagarFacturaMensual(this.idPropietario);
        } else if (seleccionTerminos == JOptionPane.NO_OPTION) {
            return;
        }
    }//GEN-LAST:event_btnFacturaMensual1MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnFacturaMensual;
    private javax.swing.JPanel btnFacturaMensual1;
    private javax.swing.JPanel btnFacturaMensual2;
    private javax.swing.JPanel btnMultas;
    private javax.swing.JPanel btnReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
