/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Control.GeneracionPDFMulta;
import Utilidades.VerificacionDatos;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MultaPropietario extends javax.swing.JFrame {
    String idEmpleado;
    String idReceptor;
    String nombreEmisor;
    String fechaEvento;
    String fechaPago;
    String costo;
    String idMulta;
    String descripcion;
    String pagoUsuario = "0";
    
    /**
     * Creates new form MultaPropietario
     */
    public MultaPropietario(String idEmpleado) {
        this.idEmpleado = idEmpleado;
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldIdReceptor = new javax.swing.JTextField();
        jTextFieldEmisor = new javax.swing.JTextField();
        jTextFieldFechaEvento = new javax.swing.JTextField();
        jTextFieldFechaPago = new javax.swing.JTextField();
        jTextFieldCosto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonMultar = new javax.swing.JButton();
        jButtonMultar1 = new javax.swing.JButton();
        jTextFieldIdMulta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 52, 78));

        jTextFieldIdReceptor.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdReceptor.setForeground(new java.awt.Color(0, 0, 0));

        jTextFieldEmisor.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmisor.setForeground(new java.awt.Color(0, 0, 0));

        jTextFieldFechaEvento.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFechaEvento.setForeground(new java.awt.Color(0, 0, 0));

        jTextFieldFechaPago.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFechaPago.setForeground(new java.awt.Color(0, 0, 0));

        jTextFieldCosto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCosto.setForeground(new java.awt.Color(0, 0, 0));

        jTextAreaDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id del receptor");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tu nombre");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha del evento");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de pago");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Costo");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripcion e información");

        jButtonMultar.setBackground(new java.awt.Color(86, 105, 129));
        jButtonMultar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonMultar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMultar.setText("Multar");
        jButtonMultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultarActionPerformed(evt);
            }
        });

        jButtonMultar1.setBackground(new java.awt.Color(86, 105, 129));
        jButtonMultar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonMultar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMultar1.setText("Limpiar");
        jButtonMultar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultar1ActionPerformed(evt);
            }
        });

        jTextFieldIdMulta.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdMulta.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Id de la multa");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Regresar al menú");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldFechaEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addComponent(jTextFieldEmisor, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldIdReceptor, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addComponent(jTextFieldCosto)
                                .addComponent(jTextFieldIdMulta, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButtonMultar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldFechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIdMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonMultar1)
                                    .addComponent(jButtonMultar))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultarActionPerformed
        DateTimeFormatter f = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        this.idReceptor = jTextFieldIdReceptor.getText();
        this.nombreEmisor = jTextFieldEmisor.getText();
        this.fechaEvento = jTextFieldFechaEvento.getText();
        this.fechaPago = jTextFieldFechaPago.getText();
        this.costo = jTextFieldCosto.getText();
        this.idMulta = jTextFieldIdMulta.getText();
        this.descripcion = jTextAreaDescripcion.getText();
        if (this.idReceptor.isEmpty() || this.nombreEmisor.isEmpty() || this.fechaEvento.isEmpty() || this.fechaPago.isEmpty() || this.costo.isEmpty() || this.idMulta.isEmpty() || this.descripcion.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debes llenar todos los espacios");
            return;
        }
        
        VerificacionDatos vd = new VerificacionDatos();
        if (vd.verificarFecha(jTextFieldFechaEvento, "dd/MM/yyyy")){
            this.fechaEvento = jTextFieldFechaEvento.getText();
        }else{
            JOptionPane.showMessageDialog(null, "Ingresa una fecha de evento en el formato dd/mm/aaaa");
            return;
        }
        
        if (vd.verificarFecha(jTextFieldFechaPago, "dd/MM/yyyy")){
            this.fechaPago = jTextFieldFechaPago.getText();
        }else{
            JOptionPane.showMessageDialog(null, "Ingresa una fecha de pago en el formato dd/mm/aaaa");
            return;
        }
        
        if (vd.verificarEntero(jTextFieldIdMulta)){
            this.idMulta = jTextFieldIdMulta.getText();
        }else{
            JOptionPane.showMessageDialog(null, "Ingresa un id de multa valido");
            return;
        }
        
        if (vd.verificarEntero(jTextFieldIdReceptor)){
            this.idReceptor = jTextFieldIdReceptor.getText();
        }else{
            JOptionPane.showMessageDialog(null, "Ingresa un id de receptor valido");
            return;
        }
        
        String fechaMulta = LocalDate.now().format(f);
        
        GeneracionPDFMulta generadorPDF = new GeneracionPDFMulta();
        generadorPDF.crearPDF(this.idReceptor, this.nombreEmisor, this.fechaEvento, fechaMulta,
                              this.fechaPago, this.costo, this.descripcion, this.idMulta, this.pagoUsuario);
        generadorPDF.registrarMultaEnCSV(this.idReceptor, this.nombreEmisor, this.fechaEvento, fechaMulta,
                                         this.fechaPago, this.costo, this.descripcion, this.idMulta, this.pagoUsuario);
    }//GEN-LAST:event_jButtonMultarActionPerformed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setForeground(Color.gray);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setForeground(Color.white);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        MenuEmpleado menuEmpleado = new MenuEmpleado(this.idEmpleado);
        menuEmpleado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButtonMultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultar1ActionPerformed
        jTextFieldIdReceptor.setText("");
        jTextFieldEmisor.setText("");
        jTextFieldFechaEvento.setText("");
        jTextFieldFechaPago.setText("");
        jTextFieldCosto.setText("");
        jTextFieldIdMulta.setText("");
        jTextAreaDescripcion.setText("");
    }//GEN-LAST:event_jButtonMultar1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMultar;
    private javax.swing.JButton jButtonMultar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldCosto;
    private javax.swing.JTextField jTextFieldEmisor;
    private javax.swing.JTextField jTextFieldFechaEvento;
    private javax.swing.JTextField jTextFieldFechaPago;
    private javax.swing.JTextField jTextFieldIdMulta;
    private javax.swing.JTextField jTextFieldIdReceptor;
    // End of variables declaration//GEN-END:variables
}
