/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;


import Beans.Propietario;
import Control.GestionPropietario;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import Utilidades.VerificacionDatos;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Registro extends javax.swing.JFrame {
    ZonedDateTime fechaActual = ZonedDateTime.now(ZoneId.of("America/Bogota"));
    DateTimeFormatter f = DateTimeFormatter.ofPattern("dd/MM/yyyy"); // estas dos variables son para la fecha de registro    


    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldFechaNacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jPasswordFieldConfirmarContraseña = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jToggleButtonRegistrar = new javax.swing.JToggleButton();
        jToggleButtonIniciar = new javax.swing.JLabel();
        jTextFieldNumContacto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldProfesion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(86, 105, 129));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Regístrate");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldNombre.setText("Nombre");
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusGained(evt);
            }
        });
        jTextFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldNombreMousePressed(evt);
            }
        });
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Identificación");

        jTextFieldId.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldId.setText("Número de identificación");
        jTextFieldId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldIdFocusGained(evt);
            }
        });
        jTextFieldId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldIdMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo");

        jTextFieldCorreo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCorreo.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldCorreo.setText("example@gmail.com");
        jTextFieldCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCorreoFocusGained(evt);
            }
        });
        jTextFieldCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldCorreoMousePressed(evt);
            }
        });

        jTextFieldFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldFechaNacimiento.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldFechaNacimiento.setText("dd/mm/aaaa");
        jTextFieldFechaNacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFechaNacimientoFocusGained(evt);
            }
        });
        jTextFieldFechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldFechaNacimientoMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de nacimiento");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");

        jPasswordFieldContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldContraseña.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordFieldContraseña.setText("****************");
        jPasswordFieldContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseñaFocusGained(evt);
            }
        });
        jPasswordFieldContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldContraseñaMousePressed(evt);
            }
        });
        jPasswordFieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContraseñaActionPerformed(evt);
            }
        });

        jPasswordFieldConfirmarContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldConfirmarContraseña.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordFieldConfirmarContraseña.setText("****************");
        jPasswordFieldConfirmarContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldConfirmarContraseñaFocusGained(evt);
            }
        });
        jPasswordFieldConfirmarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldConfirmarContraseñaMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirmar contraseña");

        jComboBoxGenero.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxGenero.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Género", "Masculino", "Femenino", "Otro" }));
        jComboBoxGenero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Género");

        jToggleButtonRegistrar.setBackground(new java.awt.Color(52, 52, 78));
        jToggleButtonRegistrar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jToggleButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonRegistrar.setText("Registrar");
        jToggleButtonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRegistrarActionPerformed(evt);
            }
        });

        jToggleButtonIniciar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jToggleButtonIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonIniciar.setText("¿Ya tienes una cuenta? Inicia Sesión");
        jToggleButtonIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonIniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButtonIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButtonIniciarMouseExited(evt);
            }
        });

        jTextFieldNumContacto.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNumContacto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNumContacto.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldNumContacto.setText("371 0540984");
        jTextFieldNumContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNumContactoFocusGained(evt);
            }
        });
        jTextFieldNumContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldNumContactoMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Numero de contacto");

        jTextFieldProfesion.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldProfesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldProfesion.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldProfesion.setText("Ingresa tu profesion");
        jTextFieldProfesion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldProfesionFocusGained(evt);
            }
        });
        jTextFieldProfesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldProfesionMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Profesion");

        jTextFieldApellido.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldApellido.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldApellido.setText("Apellidos");
        jTextFieldApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusGained(evt);
            }
        });
        jTextFieldApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldApellidoMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Apellidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordFieldConfirmarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jTextFieldNumContacto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(jPasswordFieldContraseña))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldProfesion)
                            .addComponent(jTextFieldFechaNacimiento)
                            .addComponent(jComboBoxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jToggleButtonRegistrar))
                            .addComponent(jToggleButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jToggleButtonRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButtonIniciar)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContraseñaActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreMousePressed
        limpiarCampo(jTextFieldNombre, "Nombre");
        
        verificarCampo(jTextFieldId, "Número de identificación");
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
    }//GEN-LAST:event_jTextFieldNombreMousePressed

    private void jTextFieldApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldApellidoMousePressed
        limpiarCampo(jTextFieldApellido, "Apellidos");
        
        verificarCampo(jTextFieldId, "Número de identificación");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
    }//GEN-LAST:event_jTextFieldApellidoMousePressed

    private void jTextFieldIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIdMousePressed
        limpiarCampo(jTextFieldId, "Número de identificación");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
    }//GEN-LAST:event_jTextFieldIdMousePressed

    private void jTextFieldCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCorreoMousePressed
        limpiarCampo(jTextFieldCorreo, "example@gmail.com");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
    }//GEN-LAST:event_jTextFieldCorreoMousePressed

    private void jTextFieldNumContactoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNumContactoMousePressed
        limpiarCampo(jTextFieldNumContacto, "371 0540984");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");    
    }//GEN-LAST:event_jTextFieldNumContactoMousePressed

    private void jTextFieldFechaNacimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFechaNacimientoMousePressed
        limpiarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
    }//GEN-LAST:event_jTextFieldFechaNacimientoMousePressed

    private void jTextFieldProfesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProfesionMousePressed
        limpiarCampo(jTextFieldProfesion, "Ingresa tu profesion");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
    }//GEN-LAST:event_jTextFieldProfesionMousePressed

    private void jPasswordFieldContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaMousePressed
        limpiarContraseña(jPasswordFieldContraseña, "****************");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
    }//GEN-LAST:event_jPasswordFieldContraseñaMousePressed

    private void jPasswordFieldConfirmarContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmarContraseñaMousePressed
        limpiarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
    }//GEN-LAST:event_jPasswordFieldConfirmarContraseñaMousePressed

    private void jTextFieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusGained
        limpiarCampo(jTextFieldNombre, "Nombre");
        
        verificarCampo(jTextFieldId, "Número de identificación");
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
    }//GEN-LAST:event_jTextFieldNombreFocusGained

    private void jTextFieldApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusGained
        limpiarCampo(jTextFieldApellido, "Apellidos");
        
        verificarCampo(jTextFieldId, "Número de identificación");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
    }//GEN-LAST:event_jTextFieldApellidoFocusGained

    private void jTextFieldIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIdFocusGained
        limpiarCampo(jTextFieldId, "Número de identificación");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
    }//GEN-LAST:event_jTextFieldIdFocusGained

    private void jTextFieldCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCorreoFocusGained
        limpiarCampo(jTextFieldCorreo, "example@gmail.com");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
    }//GEN-LAST:event_jTextFieldCorreoFocusGained

    private void jTextFieldNumContactoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumContactoFocusGained
        limpiarCampo(jTextFieldNumContacto, "371 0540984");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");    
    }//GEN-LAST:event_jTextFieldNumContactoFocusGained

    private void jTextFieldFechaNacimientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFechaNacimientoFocusGained
        limpiarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
    }//GEN-LAST:event_jTextFieldFechaNacimientoFocusGained

    private void jTextFieldProfesionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldProfesionFocusGained
        limpiarCampo(jTextFieldProfesion, "Ingresa tu profesion");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
    }//GEN-LAST:event_jTextFieldProfesionFocusGained

    private void jPasswordFieldContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaFocusGained
        limpiarContraseña(jPasswordFieldContraseña, "****************");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
        verificarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
    }//GEN-LAST:event_jPasswordFieldContraseñaFocusGained

    private void jPasswordFieldConfirmarContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmarContraseñaFocusGained
        limpiarContraseña(jPasswordFieldConfirmarContraseña, "****************");
        
        verificarCampo(jTextFieldApellido, "Apellidos");
        verificarCampo(jTextFieldNombre, "Nombre");
        verificarCampo(jTextFieldId, "Número de identifiación");
        verificarCampo(jTextFieldNumContacto, "371 0540984");
        verificarCampo(jTextFieldFechaNacimiento, "dd/mm/aaaa");
        verificarCampo(jTextFieldProfesion, "Ingresa tu profesion");
        verificarContraseña(jPasswordFieldContraseña, "****************");
        verificarCampo(jTextFieldCorreo, "example@gmail.com");
    }//GEN-LAST:event_jPasswordFieldConfirmarContraseñaFocusGained

    private void jToggleButtonIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonIniciarMouseEntered
        jToggleButtonIniciar.setForeground(Color.BLUE);
    }//GEN-LAST:event_jToggleButtonIniciarMouseEntered

    private void jToggleButtonIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonIniciarMouseExited
        jToggleButtonIniciar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jToggleButtonIniciarMouseExited

    private void jToggleButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRegistrarActionPerformed
        VerificacionDatos vd = new VerificacionDatos();
        double salario = Double.parseDouble("0.0"); // este se modificará luego
        // fechaAcual.format(f) es un string, asi que lo convertimos en formato f
        LocalDate fechaRegistro = LocalDate.parse(fechaActual.format(f), f);
        String nombre = jTextFieldNombre.getText();
        String correo = jTextFieldCorreo.getText();
        String id = jTextFieldId.getText();
        LocalDate fechaNacimiento = null; // Iniciamos estos 2 valores en null, para que salte el mensaje de error de campos vacios
        String numeroContacto = jTextFieldNumContacto.getText();
        String genero = (String)jComboBoxGenero.getSelectedItem();
        String contraseña = String.copyValueOf(jPasswordFieldContraseña.getPassword());
        String profesion = jTextFieldProfesion.getText();
        String apellido = jTextFieldApellido.getText();
        int rol = 1; // Predeterminado para un usuario tipo propietario
        
        if (nombre.isEmpty() || nombre.equals("Nombre") || correo.isEmpty() || correo.equals("example@gmail.com") || id.isEmpty() || id.equals("Número de identificación")|| jTextFieldFechaNacimiento.getText().equals("dd/mm/yyyy") || numeroContacto.isEmpty() || numeroContacto.equals("371 0540984")|| genero.equals("Género") || contraseña.isEmpty() || String.valueOf(jPasswordFieldContraseña.getPassword()).equals("****************") || String.valueOf(jPasswordFieldConfirmarContraseña.getPassword()).isEmpty() || String.valueOf(jPasswordFieldConfirmarContraseña.getPassword()).equals("****************")|| profesion.isEmpty() || profesion.equals("Ingresa tu profesion") || apellido.isEmpty() || apellido.equals("Apellidos")) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.");
            return;
        }

        
        if(vd.verificarEntero(jTextFieldId)){
            id = jTextFieldId.getText();
        }else{
            JOptionPane.showMessageDialog(this, "El numero de identificacion debe ser un número entero");
            return;  
        }
        
        if(vd.verificarFecha(jTextFieldFechaNacimiento, "dd/MM/yyyy")){
            fechaNacimiento = LocalDate.parse(jTextFieldFechaNacimiento.getText(), f);
        }else{
            JOptionPane.showMessageDialog(this, "La fecha de nacimiento debe estar en el formato correcto");
            return;
        }

        if(vd.verificarEntero(jTextFieldNumContacto)){
            numeroContacto = jTextFieldNumContacto.getText().trim();
            if (numeroContacto.length() != 10 && numeroContacto.length() != 7 ){
                JOptionPane.showMessageDialog(this, "Ingresa un numero de telefono válido");
                return;
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ingresa un numero de telefono valido");
            System.out.println("numero de contacto ingrsado: " + numeroContacto);
            System.out.println(numeroContacto.length());
            return;
            
        }
        
        if (!contraseña.equals(String.copyValueOf(jPasswordFieldConfirmarContraseña.getPassword()))){
            JOptionPane.showMessageDialog(this, "Confirmar contraseña y contraseña no son iguales");
            return;
        }
        
        Propietario nuevoPropietario = new Propietario(salario, fechaRegistro, nombre, correo, id, fechaNacimiento, numeroContacto, genero, contraseña, profesion, apellido, rol);
        GestionPropietario gp = new GestionPropietario();
        gp.registrarPropietario(nuevoPropietario);
        Login iniciar = new Login();
        iniciar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButtonRegistrarActionPerformed

    private void jToggleButtonIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonIniciarMouseClicked
        Login inicio = new Login();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButtonIniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }
    
    private void verificarCampo(JTextField campo, String textoPredeterminado) {
        if (campo.getText().isEmpty()) {
            campo.setText(textoPredeterminado);
            campo.setForeground(new Color(102, 102, 102));
        }
    }

    private void verificarContraseña(JPasswordField campo, String textoPredeterminado) {
        if (String.valueOf(campo.getPassword()).isEmpty()) {
            campo.setText(textoPredeterminado); // Ojo: Esto sobrescribirá el valor de la contraseña
            campo.setForeground(new Color(102, 102, 102));
        }
    }

    private void limpiarCampo(JTextField campo, String textoPredeterminado) {
        if (campo.getText().equals(textoPredeterminado)) {
            campo.setText("");
            campo.setForeground(Color.BLACK);
        }
    }

    private void limpiarContraseña(JPasswordField campo, String textoPredeterminado) {
        if (String.valueOf(campo.getPassword()).equals(textoPredeterminado)) {
            campo.setText(""); // Limpia el campo de contraseña
            campo.setForeground(Color.BLACK);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldConfirmarContraseña;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldFechaNacimiento;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumContacto;
    private javax.swing.JTextField jTextFieldProfesion;
    private javax.swing.JLabel jToggleButtonIniciar;
    private javax.swing.JToggleButton jToggleButtonRegistrar;
    // End of variables declaration//GEN-END:variables
}
